### ISSUE TITLE
Has the work finished?

### ISSUE THREAD

**Issue by flyingtango** [kozistr/AdaBound-tensorflow#1]
Has the work finished?

**Comment by kozistr** [comment]
I'm currently working on it! not sure but, maybe i think it is almost done.

But i'll take some time cuz it's my first time to implement the custom optimizer in tensorflow.

thank you in advance!

**Comment by flyingtango** [comment]
I'm very looking forward to using it as soon as possible. Thx for your effort.

**Comment by kozistr** [comment]
I think that impl & testing are done. So i'll close this issue!

if there are other issues, feel free to re-open the issue :)

thank you.
