### ISSUE TITLE
A error when run mnist_test.py and tensor input support

### ISSUE THREAD

**Issue by flyingtango** [kozistr/AdaBound-tensorflow#2]
I run the test code in docker, which includes python3.5, tensorflow 1.4. The error is below

AttributeError: 'AdaBoundOptimizer' object has no attribute 'weight_decay_rate'

Meanwhile, hope adaboundoptimizer can support tensor input like tf.train.AdamOptimizer does.

The work is great👍

**Comment by kozistr** [comment]
Firstly, thanks for reporting the bug! I just fixed that bug.

Secondly, thanks for your suggestion! maybe, that feature is already supported! I'll add more examples.

Currently, somehow, some reasons, AdaBound Optimizer doesn't work well. 
of course, i'll also try to find the issue but i'll take some time maybe.

thanks very much!

**Comment by kozistr** [comment]
bug is fixed and tensor input for lr also supported! So, i'll close this issue too!

also are there any issues. feel free to re-open the issue :) thx
