### ISSUE TITLE
weight_decay or decay?

### ISSUE THREAD

**Issue by brantbzhang** [kozistr/AdaBound-tensorflow#4]
if self._weight_decay > 0.:
            lr *= (1. / (1. + self._weight_decay * t))
weight_decay is l2 penalty，in code it is use as lr decay?

**Comment by kozistr** [comment]
oh you're right! i just used the term confusingly.

thanks for correction!

**Comment by kozistr** [comment]
I corrected the term `weight_decay` by adding a new param `decay`! So, i'll close this issue!

also are there any issues. feel free to re-open the issue :) thx
