### ISSUE TITLE
Why global step not update in apply_gradients

### ISSUE THREAD

**Issue by Jasonnor** [kozistr/AdaBound-tensorflow#5]
I see code in mnist_test.py:
```python
        # Normally the global step update is done inside of `apply_gradients`.
        # However, my version of `AdaBoundyOptimizer` doesn't do this. But if you use
        # a different optimizer, you should probably take this line out.
        if optimizer in ["adabound", "amsbound"]:
            train_op = tf.group(train_op, [global_step.assign(global_step + 1)])
```
Is there any reason that you didn't update global step in apply_gradients?
Maybe can do the same thing like [tensorflow source](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/python/training/optimizer.py#L616).

**Comment by kozistr** [comment]
Actually, there's no critical reason :) I just implemented `updating the global step` at the outside of the optimizer for updating the global step by users' taste.

maybe, your idea more makes sense and comfortable!

I'll move that operation inside of the optimizer soon! thanks for your suggestion!

**Comment by kozistr** [comment]
I updated the requested feature. So, i'll close this issue!

also are there any issues. feel free to re-open the issue :) thx
